"""Add deleted_at and is_deleted columns in ACCOUNT

Revision ID: b7632953c383
Revises: 44561ce89482
Create Date: 2026-07-17 18:19:44.277474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7632953c383'
down_revision: Union[str, Sequence[str], None] = '44561ce89482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_deleted')
    op.drop_column('accounts', 'deleted_at')
    # ### end Alembic commands ###
