"""Add created_at and updated_at columns in CUSTOMER

Revision ID: bc5c24d79dea
Revises: dbda7e42762d
Create Date: 2026-07-17 18:07:13.709882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5c24d79dea'
down_revision: Union[str, Sequence[str], None] = 'dbda7e42762d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
