"""Add deleted_at and is_deleted columns in CUSTOMER

Revision ID: c785cc113504
Revises: b7632953c383
Create Date: 2026-07-17 18:22:03.604939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c785cc113504'
down_revision: Union[str, Sequence[str], None] = 'b7632953c383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_deleted')
    op.drop_column('customers', 'deleted_at')
    # ### end Alembic commands ###
