"""Add deleted_at and is_deleted columns in TRANSACTION

Revision ID: c84a91ac1c2c
Revises: c785cc113504
Create Date: 2026-07-17 18:23:22.648157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84a91ac1c2c'
down_revision: Union[str, Sequence[str], None] = 'c785cc113504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_deleted')
    op.drop_column('transactions', 'deleted_at')
    # ### end Alembic commands ###
